[package]
name = "redlang"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.11.0"
encoding = "0.2.33"
rand = "0.8.5"
urlencoding = "2.1.2"
getrandom = "0.2.8"
base64 = "0.21.0"
serde_json = "1.0.95"
uuid = {version = "1.3.0",features = ["v4","fast-rng"]}
lazy_static = "1.4.0"
chrono = "0.4.24"
md-5 = "0.10.5"
rcnb-rs = "0.1.0"
rust-embed="6.6.1"
image = "0.24.6"
imageproc = "0.23.0"
gif = "0.12.0"
cron = "0.12.0"
hyper = { version = "0.14.25",default-features = false,features = ["server"]}
tokio = { version = "1.27.0",default-features = false,features = ["macros","fs","rt-multi-thread"] }
url = "2.3.1"
futures-util = "0.3.27"
hyper-tungstenite = "0.9.0"
tokio-tungstenite = "0.18.0" 
scopeguard = "1.1.0"
log = "0.4.17"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter","time","local-time"]}
opener = "0.6.0"
rusqlite = {version = "0.29.0",features = ["bundled"]}
screenshots = "0.5.3"
sevenz-rust = "0.2.9"
jsonpath-rust = "0.2.6"
rusttype = "0.9.3"
font-kit = "0.11.0"
markdown = "1.0.0-alpha.7"
reqwest = {version = "0.11.16",default-features = false,features = ["rustls-tls"]}
time = { version = "0.3", features = ["formatting", "macros"] }


[target.'cfg(windows)'.dependencies]
headless_chrome = {git = "https://github.com/atroche/rust-headless-chrome", features = ["fetch"]}
winreg = "*"


[profile.release]
panic = 'abort'



