[package]
name = "redlang"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = { version = "*",features = ['rustls'] }
fancy-regex = "*"
encoding = "*"
rand = "*"
sciter-rs = "*"
libloading = "*"
urlencoding = "*"
getrandom = "*"
base64 = "*"
serde_json = "*"
uuid = {version = "*",features = ["v4","fast-rng"]}
lazy_static = "*"
chrono = "*"
md-5 = "*"
rcnb-rs = "*"
rust-embed="*"
image = "*"
imageproc = "*"
gif = "*"
cron = "*"
rlua = {version = "*",features = ["lua-no-oslib","builtin-lua54"]}
headless_chrome = {git = "https://github.com/atroche/rust-headless-chrome", features = ["fetch"]}
hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }


[lib]
name = "redlang" #生成dll的文件名
crate-type = ["dylib"]

