[package]
name = "redlang"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "*"
encoding = "*"
rand = "*"
urlencoding = "*"
getrandom = "*"
base64 = "*"
serde_json = "*"
uuid = {version = "*",features = ["v4","fast-rng"]}
lazy_static = "*"
chrono = "*"
md-5 = "*"
rcnb-rs = "*"
rust-embed="*"
image = "*"
imageproc = "*"
gif = "*"
cron = "*"
hyper = { version = "*", features = ["full"] }
tokio = { version = "*", features = ["full"] }
url = "*"
futures-util = "*"
hyper-tungstenite = "*"
tokio-tungstenite = "*" 
scopeguard = "*"
log = "*"
tracing = "*"
tracing-subscriber = "*"
opener = "*"
rusqlite = {version = "*",features = ["bundled"]}
screenshots = "*"
sevenz-rust = "*"
ureq = "*"
jsonpath-rust = "*"
rusttype = "*"
font-kit = "*"

[target.'cfg(windows)'.dependencies]
headless_chrome = {git = "https://github.com/atroche/rust-headless-chrome", features = ["fetch"]}

[profile.release]
panic = 'abort'



