name: Rust

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'readme.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'readme.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: mkdir
      run: |
        mkdir outdir
        mkdir outdir\MiraiCQ
        mkdir outdir\MiraiCQ\app
        mkdir outdir\IPCTool
        mkdir outdir_t
    - name: download
      uses: robinraju/release-downloader@v1.4
      with:
        repository: "super1207/redreply"
        tag: "CommonData"
        fileName: "*"
    - name: downloadmiraicq
      uses: robinraju/release-downloader@v1.4
      with:
        repository: "super1207/MiraiCQ"
        latest: true
        fileName: "MiraiCQ.exe"
    - name: copyfile
      run: |
        cp IPCTool.dll .\outdir\IPCTool\IPCTool.dll
        cp IPCTool64.dll .\outdir\IPCTool\IPCTool64.dll
        cp MiraiCQ.exe .\outdir\MiraiCQ\MiraiCQ.exe
        cp sciter.dll .\res\sciter.dll
    - name: Build
      run: |
        $ENV:RUSTFLAGS='-C target-feature=+crt-static'
        cargo build --target=i686-pc-windows-msvc --release
    - name: UPXDeal
      uses: crazy-max/ghaction-upx@v2
      with:
          version: latest
          files: |
            .\target\i686-pc-windows-msvc\release\*.dll
          args: -fq
    - name: Deal
      run: |
        copy-item .\target\i686-pc-windows-msvc\release\*.dll -Destination .\outdir\MiraiCQ\app
        copy-item .\redlang.json -Destination .\outdir\MiraiCQ\app
        copy-item .\ovo_start_file\* -Destination .\outdir
        Compress-Archive .\outdir\* 红色问答.zip
        mv 红色问答.zip 红色问答.opk
        cp 红色问答.opk outdir_t
    - name: upload file
      uses: actions/upload-artifact@v2
      with:
        name: upload files
        path: 
            .\outdir_t
